/* Generated by scripts/export_residual_to_c.py. Do not edit by hand. */
#ifndef CPTSERVO_COEFFS_H
#define CPTSERVO_COEFFS_H

#if defined(__GNUC__)
#define CPT_COEFF_UNUSED __attribute__((unused))
#else
#define CPT_COEFF_UNUSED
#endif

#define CPT_RESIDUAL_LIMIT_HZ (40)
#define CPT_RF_LIMIT_HZ (1000)
#define CPT_CONTROL_DT_S (0.001)
#define CPT_T_NOM_K (333.14999999999998)
#define CPT_B_NOM_UT (50)
#define CPT_I_NOM (1)
#define CPT_INTENSITY_TAU_S (0.01)
#define CPT_MAX_SENSOR_STEP_T_K (2)
#define CPT_MAX_SENSOR_STEP_B_UT (5)
#define CPT_MAX_SENSOR_STEP_I_NORM (0.10000000000000001)
#define CPT_ERR_INTEGRAL_CLIP (0.050000000000000003)
#define CPT_RESIDUAL_MODE (1)
#define CPT_OUTPUT_FEATURE_SKIP (1)

enum {
    CPT_HIDDEN_SIZE = 8,
    CPT_FEATURE_DIM = 14,
    CPT_ERR_WINDOW_SIZE = 16
};

static const double LQR_DT CPT_COEFF_UNUSED = 0.001;
static const double LQR_RF_LIMIT CPT_COEFF_UNUSED = 1000;
static const double LQR_K[2] CPT_COEFF_UNUSED = { 6543.4821106445643, 99942.501328817307 };
static const double LQR_AD[2][2] CPT_COEFF_UNUSED = {
    { 0.36787944117144233, 0 },
    { 0.00063212055882855766, 1 }
};
static const double LQR_BD[2] CPT_COEFF_UNUSED = { 1.5170893411885384e-08, 8.8291065881146174e-09 };

static const double CFC_W_C[8][14] CPT_COEFF_UNUSED = {
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};
static const double CFC_U_C[8][8] CPT_COEFF_UNUSED = {
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 }
};
static const double CFC_B_C[8] CPT_COEFF_UNUSED = { 0, 0, 0, 0, 0, 0, 0, 0 };
static const double CFC_W_TAU[8][14] CPT_COEFF_UNUSED = {
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};
static const double CFC_U_TAU[8][8] CPT_COEFF_UNUSED = {
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 0, 0 }
};
static const double CFC_B_TAU[8] CPT_COEFF_UNUSED = { 0, 0, 0, 0, 0, 0, 0, 0 };
static const double CFC_W_OUT[8] CPT_COEFF_UNUSED = { 0, 0, 0, 0, 0, 0, 0, 0 };
static const double CFC_W_FEAT_OUT[14] CPT_COEFF_UNUSED = { 15, 0, 0, -0.10000000000000001, 0, 0, 3.9260892663867391, 0, 0, 0, 0, 0, 0, 0 };
static const double CFC_B_OUT[1] CPT_COEFF_UNUSED = { 0 };

#endif /* CPTSERVO_COEFFS_H */
