"""Export a CfCDirectController checkpoint to MCU-friendly C coefficients."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from cptservo.baselines.rh_lqr import RHLQRController  # noqa: E402
from cptservo.policy.ml_research import CfCDirectController  # noqa: E402


def _fmt(x: float) -> str:
    return f"{float(x):.17g}"


def _flat(values: Iterable[float]) -> str:
    return ", ".join(_fmt(v) for v in values)


def _array_1d(name: str, arr: np.ndarray) -> str:
    return f"static const double {name}[{arr.size}] CPT_COEFF_UNUSED = {{ {_flat(arr)} }};\n"


def _array_2d(name: str, arr: np.ndarray) -> str:
    rows = []
    for row in arr:
        rows.append("    { " + _flat(row) + " }")
    body = ",\n".join(rows)
    return (
        f"static const double {name}[{arr.shape[0]}][{arr.shape[1]}] "
        f"CPT_COEFF_UNUSED = {{\n{body}\n}};\n"
    )


def _load_payload(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def export(checkpoint: Path, output: Path) -> None:
    controller = CfCDirectController.load(checkpoint)
    lqr = RHLQRController.from_recipe()
    payload = _load_payload(checkpoint)

    cfg = controller.config
    sensor = cfg.sensor_config
    weights = controller.weights
    h = int(cfg.hidden_size)
    f = int(controller.feature_dim)

    output.parent.mkdir(parents=True, exist_ok=True)
    text = [
        "/* Generated by scripts/export_residual_to_c.py. Do not edit by hand. */\n",
        "#ifndef CPTSERVO_COEFFS_H\n",
        "#define CPTSERVO_COEFFS_H\n\n",
        "#if defined(__GNUC__)\n",
        "#define CPT_COEFF_UNUSED __attribute__((unused))\n",
        "#else\n",
        "#define CPT_COEFF_UNUSED\n",
        "#endif\n\n",
        f"#define CPT_RESIDUAL_LIMIT_HZ ({_fmt(cfg.residual_limit_Hz)})\n",
        f"#define CPT_RF_LIMIT_HZ ({_fmt(cfg.rf_limit_Hz)})\n",
        f"#define CPT_CONTROL_DT_S ({_fmt(cfg.control_dt_s)})\n",
        f"#define CPT_T_NOM_K ({_fmt(sensor.T_nom_K)})\n",
        f"#define CPT_B_NOM_UT ({_fmt(sensor.B_nom_uT)})\n",
        f"#define CPT_I_NOM ({_fmt(sensor.I_nom)})\n",
        f"#define CPT_INTENSITY_TAU_S ({_fmt(sensor.intensity_tau_s)})\n",
        f"#define CPT_MAX_SENSOR_STEP_T_K ({_fmt(sensor.max_sensor_step_T_K)})\n",
        f"#define CPT_MAX_SENSOR_STEP_B_UT ({_fmt(sensor.max_sensor_step_B_uT)})\n",
        f"#define CPT_MAX_SENSOR_STEP_I_NORM ({_fmt(sensor.max_sensor_step_I_norm)})\n",
        f"#define CPT_ERR_INTEGRAL_CLIP ({_fmt(cfg.err_integral_clip)})\n",
        f"#define CPT_RESIDUAL_MODE ({1 if cfg.residual_mode else 0})\n",
        f"#define CPT_OUTPUT_FEATURE_SKIP ({1 if cfg.output_feature_skip else 0})\n\n",
        "enum {\n",
        f"    CPT_HIDDEN_SIZE = {h},\n",
        f"    CPT_FEATURE_DIM = {f},\n",
        "    CPT_ERR_WINDOW_SIZE = 16\n",
        "};\n\n",
        f"static const double LQR_DT CPT_COEFF_UNUSED = {_fmt(lqr.control_dt_s)};\n",
        f"static const double LQR_RF_LIMIT CPT_COEFF_UNUSED = {_fmt(lqr.rf_limit_Hz)};\n",
        _array_1d("LQR_K", np.asarray(lqr.K, dtype=np.float64).reshape(-1)),
        _array_2d("LQR_AD", np.asarray(lqr._Ad, dtype=np.float64)),
        _array_1d("LQR_BD", np.asarray(lqr._Bd, dtype=np.float64).reshape(-1)),
        "\n",
        _array_2d("CFC_W_C", np.asarray(weights["W_c"], dtype=np.float64)),
        _array_2d("CFC_U_C", np.asarray(weights["U_c"], dtype=np.float64)),
        _array_1d("CFC_B_C", np.asarray(weights["b_c"], dtype=np.float64)),
        _array_2d("CFC_W_TAU", np.asarray(weights["W_tau"], dtype=np.float64)),
        _array_2d("CFC_U_TAU", np.asarray(weights["U_tau"], dtype=np.float64)),
        _array_1d("CFC_B_TAU", np.asarray(weights["b_tau"], dtype=np.float64)),
        _array_1d("CFC_W_OUT", np.asarray(weights["W_out"], dtype=np.float64)),
        _array_1d("CFC_W_FEAT_OUT", np.asarray(weights["W_feat_out"], dtype=np.float64)),
        _array_1d("CFC_B_OUT", np.asarray(weights["b_out"], dtype=np.float64)),
        "\n#endif /* CPTSERVO_COEFFS_H */\n",
    ]
    output.write_text("".join(text), encoding="utf-8")

    nonzero_skip = int(np.count_nonzero(np.asarray(weights["W_feat_out"])))
    print(f"Wrote {output}")
    print(f"checkpoint: {checkpoint}")
    print(f"hidden_size={h} feature_dim={f} residual_mode={cfg.residual_mode}")
    print(f"rf_limit_Hz={cfg.rf_limit_Hz} residual_limit_Hz={cfg.residual_limit_Hz}")
    print(f"LQR_K=[{_flat(np.asarray(lqr.K).reshape(-1))}]")
    print(f"W_feat_out nonzero entries={nonzero_skip}")
    print(f"source checkpoint keys={', '.join(payload.keys())}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "checkpoint",
        nargs="?",
        default=ROOT / "models" / "cfc_residual_m11_promoted.json",
        type=Path,
        help="CfCDirectController JSON checkpoint",
    )
    parser.add_argument(
        "--output",
        default=ROOT / "c_export" / "cptservo_coeffs.h",
        type=Path,
        help="Output C header path",
    )
    args = parser.parse_args()
    export(args.checkpoint, args.output)


if __name__ == "__main__":
    main()
